services:
  - type: web
    name: sam-gov-api
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PORT
        value: 10000
